// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/agents/run': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/agents/run.post').default>>>>
    }
    '/api/analyst/chat-clear': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analyst/chat-clear.post').default>>>>
    }
    '/api/analyst/chat-history': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analyst/chat-history.get').default>>>>
    }
    '/api/analyst/chat-save': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analyst/chat-save.post').default>>>>
    }
    '/api/analyst/chat': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analyst/chat.post').default>>>>
    }
    '/api/analyst/db-connect': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analyst/db-connect.post').default>>>>
    }
    '/api/analyst/db-delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analyst/db-delete.post').default>>>>
    }
    '/api/analyst/db-introspect': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analyst/db-introspect').default>>>>
    }
    '/api/analyst/db-list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analyst/db-list.get').default>>>>
    }
    '/api/analyst/db-query': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analyst/db-query.post').default>>>>
    }
    '/api/analyst/db-test': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analyst/db-test.post').default>>>>
    }
    '/api/analyst/query': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analyst/query.post').default>>>>
    }
    '/api/analyst/sql-gen': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analyst/sql-gen.post').default>>>>
    }
    '/api/analyst/summary': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analyst/summary.post').default>>>>
    }
    '/api/analytics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analytics/index.get').default>>>>
    }
    '/api/bot/cron': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot/cron.post').default>>>>
    }
    '/api/bot/join': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot/join.post').default>>>>
    }
    '/api/bot/leave': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot/leave.post').default>>>>
    }
    '/api/bot/respond': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot/respond.post').default>>>>
    }
    '/api/bot/schedule-delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot/schedule-delete.post').default>>>>
    }
    '/api/bot/schedule': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot/schedule.post').default>>>>
    }
    '/api/bot/schedules': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot/schedules.get').default>>>>
    }
    '/api/bot/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bot/status.get').default>>>>
    }
    '/api/files/delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/files/delete.post').default>>>>
    }
    '/api/files': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/files/index.get').default>>>>
    }
    '/api/files/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/files/upload.post').default>>>>
    }
    '/api/integrations/disconnect': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/integrations/disconnect.post').default>>>>
    }
    '/api/integrations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/integrations/index.get').default>>>>
    }
    '/api/integrations/save': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/integrations/save.post').default>>>>
    }
    '/api/integrations/test': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/integrations/test.post').default>>>>
    }
    '/api/meetings/analyze': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/meetings/analyze.post').default>>>>
    }
    '/api/meetings/clear-transcript': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/meetings/clear-transcript.post').default>>>>
    }
    '/api/meetings/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/meetings/create.post').default>>>>
    }
    '/api/meetings/delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/meetings/delete.post').default>>>>
    }
    '/api/meetings/end': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/meetings/end.post').default>>>>
    }
    '/api/meetings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/meetings/index.get').default>>>>
    }
    '/api/meetings/process': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/meetings/process.post').default>>>>
    }
    '/api/meetings/rename': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/meetings/rename.post').default>>>>
    }
    '/api/meetings/transcribe': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/meetings/transcribe.post').default>>>>
    }
    '/api/messages': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/messages/index.post').default>>>>
    }
    '/api/tasks/approve': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/approve.post').default>>>>
    }
    '/api/voice/respond': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/voice/respond.post').default>>>>
    }
    '/api/voice/synthesize': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/voice/synthesize.post').default>>>>
    }
    '/api/workflows': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workflows/index').default>>>>
    }
    '/api/workflows/run': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workflows/run.post').default>>>>
    }
    '/api/workspace/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workspace/create.post').default>>>>
    }
    '/api/workspace/invite-info': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workspace/invite-info.get').default>>>>
    }
    '/api/workspace/invite-manage': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workspace/invite-manage.post').default>>>>
    }
    '/api/workspace/invite': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workspace/invite.post').default>>>>
    }
    '/api/workspace/join': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workspace/join.post').default>>>>
    }
    '/api/workspace/members': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workspace/members.get').default>>>>
    }
    '/api/workspace/remove-member': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workspace/remove-member.post').default>>>>
    }
    '/api/workspace/runs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workspace/runs.get').default>>>>
    }
    '/api/workspace/schedule': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workspace/schedule.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}